[package]
name = "libsql-python"
version = "0.0.34"
edition = "2021"

[lib]
name = "libsql_experimental"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
libsql = { version = "0.3.5"  }
tokio = { version = "1.29.1", features = [ "rt-multi-thread" ] }
tracing-subscriber = "0.3"
