version: '3'

services:

  sqld:
    build:
      context: https://github.com/tursodatabase/libsql.git
    command: [ "/bin/sqld", "--admin-listen-addr", "0.0.0.0:9090" ]

  tests:
    build:
      context: .
    command: "pytest -rsx"
    depends_on:
      sqld:
        condition: service_started
    environment:
      - SQLD_HOST=sqld
